<#
  ChemSurplus — industry build engine
  -------------------------------------------------------------
  Reads seo/industries.json and generates:
    * assets/js/industries.js          (runtime taxonomy — DO NOT hand-edit)
    * industries/<slug>.html           (per-industry SEO landing pages)
    * sitemap.xml                       (complete: core + categories + industries)

  Single source of truth = seo/industries.json (+ seo/keywords.json for category URLs).
  USAGE: powershell -ExecutionPolicy Bypass -File build-industries.ps1
#>

$ErrorActionPreference = "Stop"
$root    = $PSScriptRoot
$indPath = Join-Path $root "seo\industries.json"
$kwPath  = Join-Path $root "seo\keywords.json"
$supPath = Join-Path $root "seo\suppliers.json"
$indDir  = Join-Path $root "industries"
if (!(Test-Path $indDir)) { New-Item -ItemType Directory -Path $indDir | Out-Null }

$data    = Get-Content $indPath -Raw -Encoding UTF8 | ConvertFrom-Json
$sup     = Get-Content $supPath -Raw -Encoding UTF8 | ConvertFrom-Json
$inds    = $data.industries
$supMap  = @{}; foreach ($s in $sup.suppliers) { $supMap[$s.slug] = $s.name }
$domain  = "https://www.chemsurplus.com"
$updated = $data.meta.lastUpdated

Write-Host "ChemSurplus industry build ($($inds.Count) industries)" -ForegroundColor Cyan
Write-Host ("-" * 60)

# ---------- 1) runtime industries.js ----------
$runtime = $inds | ForEach-Object {
  [pscustomobject]@{
    slug=$_.slug; name=$_.name; icon=$_.icon; tagline=$_.tagline;
    categories=$_.categories; exampleChemicals=$_.exampleChemicals;
    suppliers=$_.suppliers; pains=$_.pains
  }
}
$json = $runtime | ConvertTo-Json -Depth 6
$jsHeader = "/* GENERATED by build-industries.ps1 from seo/industries.json - DO NOT EDIT. */`r`nconst INDUSTRIES = "
$jsFooter = ";`r`nfunction industryIconKey(slug){var i=INDUSTRIES.find(function(x){return x.slug===slug});return i?i.icon:'beaker';}"
($jsHeader + $json + $jsFooter) | Out-File -FilePath (Join-Path $root "assets\js\industries.js") -Encoding utf8
Write-Host "  [+] assets/js/industries.js" -ForegroundColor Green

# ---------- 1b) runtime suppliers.js (verified broker profiles) ----------
$supRuntime = @{}
foreach ($s in $sup.suppliers) {
  $supRuntime[$s.slug] = [pscustomobject]@{
    name=$s.name; tier="Verified broker"; since=$s.since;
    specialty=$s.specialty; regions=($s.regions -join " / "); url=$s.url
  }
}
$supJson = $supRuntime | ConvertTo-Json -Depth 5
$supJs = "/* GENERATED by build-industries.ps1 from seo/suppliers.json - DO NOT EDIT. */`r`n" +
         "const SUPPLIERS = $supJson;`r`n" +
         "function supplierInfo(slug){return SUPPLIERS[slug] || {name:'Verified supplier',tier:'Verified broker'};}`r`n" +
         "function supplierName(slug){return supplierInfo(slug).name;}"
$supJs | Out-File -FilePath (Join-Path $root "assets\js\suppliers.js") -Encoding utf8
Write-Host "  [+] assets/js/suppliers.js" -ForegroundColor Green

# ---------- 2) industry landing pages ----------
function Header60 {
@"
<header class="site-header">
  <div class="container nav">
    <a href="../index.html" class="brand">
      <svg class="brand__mark" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#0e6b5c"/><path d="M16 9h8M17 9v7l-6 11a2 2 0 0 0 1.7 3h14.6a2 2 0 0 0 1.7-3l-6-11V9" stroke="#16c79a" stroke-width="2" stroke-linejoin="round"/></svg>
      ChemSurplus</a>
    <ul class="nav__links">
      <li><a href="../buy.html">Buy chemicals</a></li><li><a href="../sell.html">Sell surplus</a></li>
      <li><a href="../how-it-works.html">How it works</a></li><li><a href="../index.html#industries">Industries</a></li>
    </ul>
    <div class="nav__cta">
      <a href="../sell.html" class="btn btn--ghost">List surplus</a>
      <a href="../buy.html" class="btn btn--primary">Browse marketplace</a>
      <button class="nav__toggle" data-nav-toggle aria-label="Menu"><svg width="26" height="26" viewBox="0 0 24 24" stroke="#0a1f1b" stroke-width="2"><path d="M3 6h18M3 12h18M3 18h18"/></svg></button>
    </div>
  </div>
</header>
"@
}

foreach ($ind in $inds) {
  $chips = ($ind.exampleChemicals | ForEach-Object { "<span class=""tag tag--gray"">$_</span>" }) -join " "
  $pains = ($ind.pains | ForEach-Object { "<li>$_</li>" }) -join ""
  $supList = ($ind.suppliers | ForEach-Object { "<span class=""pill"">$($supMap[$_])</span>" }) -join " "
  $catLinks = ($ind.categories | ForEach-Object { "<a class=""pill"" href=""../buy.html?cat=$_&industry=$($ind.slug)"">$_</a>" }) -join " "
  $siblings = ($inds | Where-Object { $_.slug -ne $ind.slug } | ForEach-Object { "<a class=""pill"" href=""$($_.slug).html"">$($_.name)</a>" }) -join " "
  $url = "$domain/industries/$($ind.slug).html"

  $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$($ind.title)</title>
<meta name="description" content="$($ind.metaDescription)">
<link rel="canonical" href="$url">
<meta name="robots" content="index, follow, max-image-preview:large">
<meta property="og:type" content="website">
<meta property="og:title" content="$($ind.title)">
<meta property="og:description" content="$($ind.metaDescription)">
<meta property="og:url" content="$url">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&display=swap" media="print" onload="this.media='all'">
<noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&display=swap"></noscript>
<link rel="stylesheet" href="../assets/css/styles.css">
<link rel="icon" href="../assets/img/favicon.svg" type="image/svg+xml">
<script type="application/ld+json">
{"@context":"https://schema.org","@graph":[
{"@type":"BreadcrumbList","itemListElement":[
{"@type":"ListItem","position":1,"name":"Home","item":"$domain/"},
{"@type":"ListItem","position":2,"name":"Industries","item":"$domain/#industries"},
{"@type":"ListItem","position":3,"name":"$($ind.name)","item":"$url"}]},
{"@type":"CollectionPage","name":"$($ind.title)","url":"$url","about":"Surplus chemicals for the $($ind.name) industry"}]}
</script>
</head>
<body>
$(Header60)

<section class="hero">
  <div class="container" style="padding:64px 0 40px">
    <div class="flex items-center gap" style="gap:1rem">
      <div class="card__ic" style="width:60px;height:60px" id="indIcon"></div>
      <div>
        <p class="eyebrow" style="margin:0">Industry · $($ind.name)</p>
        <h1 style="margin:.2rem 0">Surplus chemicals for $($ind.name)</h1>
      </div>
    </div>
    <p class="lead mt-2">$($ind.tagline) Every lot is documented (SDS/COA) and sourced from a verified broker — you only see what's relevant to $($ind.name).</p>
    <div class="flex gap wrap mt-3">
      <a href="../buy.html?industry=$($ind.slug)" class="btn btn--primary btn--lg">See $($ind.name) surplus &rarr;</a>
      <a href="../sell.html" class="btn btn--ghost btn--lg">List $($ind.name) surplus</a>
    </div>
    <p class="muted mt-3" style="font-size:.85rem">Commonly available: $chips</p>
  </div>
</section>

<section class="section--tight" style="background:#fff;border-top:1px solid var(--line)">
  <div class="container grid grid--2">
    <div>
      <h2>What $($ind.name) buyers struggle with</h2>
      <ul class="prose">$pains</ul>
      <p class="muted">ChemSurplus filters the entire surplus market down to lots that fit $($ind.name) — no firehose, no irrelevant chemistry.</p>
    </div>
    <div>
      <h2>Relevant categories</h2>
      <div class="internal-links">$catLinks</div>
      <h2 class="mt-3">Suppliers we aggregate for $($ind.name)</h2>
      <div class="internal-links">$supList</div>
      <p class="muted" style="font-size:.85rem">We're the interface; these verified brokers hold the stock.</p>
    </div>
  </div>
</section>

<section class="section--tight">
  <div class="container">
    <h2 class="center">Other industries</h2>
    <div class="internal-links" style="justify-content:center">$siblings</div>
  </div>
</section>

<section class="section--tight">
  <div class="container">
    <div class="cta-band flex between items-center wrap gap">
      <div style="max-width:38ch"><h2>See only $($ind.name) surplus.</h2><p>Pick your industry once — the marketplace personalizes to you.</p></div>
      <a href="../buy.html?industry=$($ind.slug)" class="btn btn--accent btn--lg">Open $($ind.name) marketplace &rarr;</a>
    </div>
  </div>
</section>

<footer class="site-footer">
  <div class="container"><div class="footer-bottom" style="border:0;margin:0;padding:0">
    <span>&copy; 2026 ChemSurplus &mdash; surplus chemicals for $($ind.name).</span>
    <span><a href="../index.html" style="color:#9fb3ad">Home</a> &middot; <a href="../buy.html" style="color:#9fb3ad">Buy</a> &middot; <a href="../sell.html" style="color:#9fb3ad">Sell</a></span>
  </div></div>
</footer>
<script src="../assets/js/app.js"></script>
<script src="../assets/js/industries.js"></script>
<script>document.getElementById("indIcon").innerHTML = icon("$($ind.icon)");</script>
</body>
</html>
"@
  $html | Out-File -FilePath (Join-Path $indDir "$($ind.slug).html") -Encoding utf8
  Write-Host ("  [+] industries/{0,-22} -> {1}" -f "$($ind.slug).html", $ind.name) -ForegroundColor Green
}

# ---------- 3) complete sitemap ----------
$cats = (Get-Content $kwPath -Raw -Encoding UTF8 | ConvertFrom-Json).landingPages
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$sb.AppendLine('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
$core = @(
  @{l="$domain/";p="1.0";f="daily"}, @{l="$domain/buy.html";p="0.9";f="daily"},
  @{l="$domain/sell.html";p="0.9";f="weekly"}, @{l="$domain/how-it-works.html";p="0.6";f="monthly"},
  @{l="$domain/ecosystem.html";p="0.7";f="monthly"}
)
foreach ($c in $core) { [void]$sb.AppendLine("  <url><loc>$($c.l)</loc><lastmod>$updated</lastmod><changefreq>$($c.f)</changefreq><priority>$($c.p)</priority></url>") }
foreach ($i in $inds) { [void]$sb.AppendLine("  <url><loc>$domain/industries/$($i.slug).html</loc><lastmod>$updated</lastmod><changefreq>weekly</changefreq><priority>0.85</priority></url>") }
foreach ($c in $cats) { [void]$sb.AppendLine("  <url><loc>$domain/categories/$($c.slug).html</loc><lastmod>$updated</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>") }
[void]$sb.AppendLine('</urlset>')
$sb.ToString() | Out-File -FilePath (Join-Path $root "sitemap.xml") -Encoding utf8

Write-Host ("-" * 60)
Write-Host ("Done. {0} industries + industries.js + sitemap ({1} URLs)." -f $inds.Count, ($core.Count + $inds.Count + $cats.Count)) -ForegroundColor Cyan
