<#
  ChemSurplus - catalog aggregator.
  Reads data/broker-feeds.json (per-broker inventory feeds) and aggregates every
  broker's lots into one catalog -> assets/js/catalog.js (const SEED_LISTINGS).
  Each lot is stamped with supplier = <broker slug>. This is the "aggregate products
  from brokers" pipeline. Re-run after editing feeds (or after API ingestion sync).
  USAGE: powershell -ExecutionPolicy Bypass -File build-catalog.ps1
  Keep this source pure ASCII.
#>
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$feed = Get-Content (Join-Path $root "data\broker-feeds.json") -Raw -Encoding UTF8 | ConvertFrom-Json

$all = @()
$summary = @()
foreach ($b in $feed.brokers) {
  $n = 0
  foreach ($lot in $b.lots) {
    $lot | Add-Member -NotePropertyName supplier -NotePropertyValue $b.broker -Force
    $all += $lot
    $n++
  }
  $summary += [pscustomobject]@{ broker=$b.broker; name=$b.name; lots=$n; synced=$b.synced }
}

# stable order: newest-id-ish first is fine; keep feed order
$json = $all | ConvertTo-Json -Depth 6
$sourcesJson = $summary | ConvertTo-Json -Depth 4
$js = "/* GENERATED by build-catalog.ps1 from data/broker-feeds.json - DO NOT EDIT. */`r`n" +
      "/* Aggregated catalog: $($all.Count) lots across $($feed.brokers.Count) verified brokers. */`r`n" +
      "const CS_CATALOG = $json;`r`n" +
      "const CS_SOURCES = $sourcesJson;"
$js | Out-File -FilePath (Join-Path $root "assets\js\catalog.js") -Encoding utf8

Write-Host "ChemSurplus catalog aggregation" -ForegroundColor Cyan
Write-Host ("-" * 50)
foreach ($s in $summary) { Write-Host ("  {0,-16} {1,2} lots  (synced {2})" -f $s.name, $s.lots, $s.synced) -ForegroundColor Green }
Write-Host ("-" * 50)
Write-Host ("  [+] assets/js/catalog.js : $($all.Count) lots aggregated from $($feed.brokers.Count) brokers") -ForegroundColor Cyan
